apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/bal-gopal/infrastructure.git
  username: Bal-Gopal
  password: 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
